# Métodos matemáticos

# Linear Algebra

# Basic modules

We will employ two basic modules: **numpy** and **SciPy**. We have already made a quick introduction to **numpy**. **SciPy** is an open-source Python library built on top of NumPy that offers a wide range of scientific and technical computing capabilities. It provides a collection of functions and tools for various scientific domains, including mathematics, physics, engineering, and data analysis.

**numpy** is typically imported as a whole:

In [30]:
import numpy as np

In contrast, **scipy** sub-modules are typically imported as you need them. For instante:

In [31]:
import scipy.linalg as linalg

In [32]:
from scipy.linalg import solve

# Matrix Algebra - an introduction

A **matrix** a is two-dimensional array of numbers.

$$
\begin{equation}
\textbf{A}= \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] \hspace{1cm}
\textbf{B} = \left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right] \hspace{1cm}
\textbf{C} = \left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] \hspace{1cm}
\textbf{d} = \left[ \begin{array}{r} 2 \\ 6 \end{array}\right]
\end{equation}
$$

When discussing matrices it is common to talk about their dimensions, or shape, by specifying the number of rows and columns.  The number of rows is usually listed first. For instance:

- $\textbf{A}$ and $\textbf{C}$ are $2\times 2$ matrices
- $\textbf{B}$ is a $2 \times 3$ matrix
- $\textbf{d}$ is a $2 \times 1 $ matrix.  

Matrices that have only 1 column, such as $\textbf{d}$, are commonly referred to as **vectors**.


Matrices can be represented in python as numpy arrays:

In [33]:
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,1]])
C = np.array([[-2,1],[4,1]])
d = np.array([2,6])

## Name conventions

When naming matrices and vectors the following convention is commonly used:

- Matrices are named using bold uppercase letters
- Vectors are named using bold lowercase letters


when refering to individual entries of matrices, the common notation is a lowercase letter with subscripts to denote the position of the entry in the matrix:

$$\textbf{A} = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix} $$

When refering to generic entries, we use variables in the subscripts, such as $a_{ij}$.


## Operations on matrices

There are three algebraic operations for matrices that we will need to perform.  For our definitions let us suppose that $\textbf{A}$ and $\textbf{C}$ are $m \times n$ matrices, $\textbf{B}$ is an $n \times k$ matrix, and $c$ is a number.  When discussing algebra involving matrices and numbers, the numbers are usually referred to as **scalars**.

1. A matrix of any shape can be multiplied by a scalar.  The result is that all entries are multiplied by that scalar.  Using the subscript notation, we would write

$$
(c\textbf{A})_{ij} = ca_{ij}
$$

In [34]:
# multiplication of a matrix by a scalar. A is a numpy array
c = 5
cA = c*A
print(cA)
### would this operation work if A was a list?

[[ 5 15]
 [10  5]]



2. Two matrices that *have the same shape* can be added.  The result is that all corresponding entries are added.

$$
(\textbf{A}+\textbf{C})_{ij} = a_{ij} + c_{ij}
$$



In [36]:
# sum of two matrices. A and C are numpy arrays
A_p_C = A+C
C_p_A = C+A
### Check if A_p_C is equal to C_p_A
### would this operation work if A and/or C were lists?

3. If the number of columns of matrix $\textbf{A}$ is equal to the number of rows of matrix $B$, the matrices can be multiplied in the order $\textbf{A}$, $\textbf{B}$.  The result will be a new matrix $\textbf{AB}$, that has the same number of rows as $\textbf{A}$ and the same number of columns as $\textbf{B}$.  The entries $(\textbf{AB})_{ij}$ will be the following combination of the entries of row $i$ of $\textbf{A}$ and column $j$ of $\textbf{B}$.

$$
(\textbf{AB})_{ij} = \sum_{k=1}^n a_{ik}b_{kj}
$$


In [37]:
# Matrix multiplication. A and B are numpy arrays
A_times_B = A@B
A_times_B
### would this operation work if A and/or C were lists?

array([[ 0, -6,  7],
       [ 5, -2,  9]])

The last operation, known as **matrix multiplication**, is the most complex and least intuitive of the three.  No doubt this last formula is a bit intimidating the first time we read it.  Let's give some examples to clarify.

1.  The multiplication of a number and a matrix:

$$
\begin{equation}
3\textbf{A} = 3\left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
= \left[ \begin{array}{rr} 3 & 9 \\ 6 & 3 \end{array}\right]
\end{equation}
$$

2. The sum of two matrices of the same shape:

$$
\begin{equation}
\textbf{A} + \textbf{C} = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] +
\left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right]
= \left[ \begin{array}{rr} -1 & 4 \\ 6 & 2 \end{array}\right]
\end{equation}
$$

3.  The multiplication of two matrices:

$$
\begin{equation}
\textbf{AB} = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
\left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right]
 = \left[ \begin{array}{rrr} 0 & -6 & 7  \\  5 & -2 & 9  \end{array}\right]
 \end{equation}
$$

To clarify what happens in the  matrix multiplication, lets calculate two of the entries in detail.

$$
\begin{eqnarray*}
(\textbf{AB})_{12} & = & 1\times 0 + 3 \times (-2) = -6 \\
(\textbf{AB})_{23} & = & 2 \times 4 + 1 \times 1 = 9
\end{eqnarray*}
$$

These matrix operations are all built into NumPy, but we have to use the symbol $\texttt{@}$ instead of $\texttt{*}$ for matrix multiplication.

### Properties of matrix operations

It is useful to observe that some common algebraic properties hold true for matrix multiplication.  Let $A$, $B$, and $C$ be matrices, and $k$ be a scalar.  The associative and distributive properties stated here hold for matrix multiplication.

$$
\begin{equation}
k(\textbf{A}+\textbf{B}) = k\textbf{A} + k\textbf{B}
\end{equation}
$$

$$
\begin{equation}
\textbf{C}(\textbf{A}+\textbf{B}) = \textbf{CA} + \textbf{CB}
\end{equation}
$$

$$
\begin{equation}
\textbf{A}(\textbf{BC}) = (\textbf{AB})\textbf{C}
\end{equation}
$$

**These statements only make sense of course if the matrices have dimensions that allow for the operations.**

It is also worth noting that the commutative property does not generally hold for matrix multiplication.  Suppose for example that $A$ and $B$ are both $3\times 3$ matrices.  It is **not true in general** that $AB = BA$.  One example with random matrices is enough to prove this point.

In [38]:
# quick proof that commutative property doesn't hold for matrix multiplication
A@C == C@A

array([[False, False],
       [False, False]])

## Matrix transposes

Another common idea that we will find useful is that of the matrix transpose.  The **transpose** of a matrix $A$ is another matrix, $A^T$, defined so that its columns are the rows of $A$.  To build $A^T$, we simple swap the row index with the column index for every entry, $a^T_{ij} = a_{ji}$.  Two examples should be enough to clarify this definition.

$$
\begin{equation}
\textbf{A} = \left[ \begin{array}{rrr} 5 & 4 & 0 \\ 1 & 8 & 3 \\ 6 & 7 & 2\end{array}\right] \hspace{1cm}
\textbf{A}^T = \left[ \begin{array}{rrr} 5 & 1 & 6 \\ 4 & 8 & 7 \\ 0 & 3 & 2\end{array}\right] \hspace{1cm}
\end{equation}
$$


NumPy array objects have a method named $\texttt{transpose}$ for this purpose.

In [39]:
A

array([[1, 3],
       [2, 1]])

In [40]:
# first alternative: using the transpose function
A_T = np.transpose(A)
A_T

array([[1, 2],
       [3, 1]])

In [41]:
# second alternative: using the numpy array transpose method
A_T = A.T
A_T

array([[1, 2],
       [3, 1]])

When a matrix $\textbf{A}$ is equal to its own transpose, it has the property of being symmetric across its main diagonal. For this reason a matrix $\textbf{A}$ is said to be **symmetric** if $\textbf{A} = \textbf{A}^T$. Equivalently, we can say that $\textbf{A}$ is symmetric if $a_{ij} = a_{ji}$ for every entry $a_{ij}$ in the matrix.  The matrix $\textbf{P}$ below is one such example.

$$
\begin{equation}
\textbf{P} = \left[ \begin{array}{rrr} 1 & 0 & 6 \\ 0 & 3 & 5 \\ 6 & 5 & -2\end{array}\right] \hspace{1cm}
\end{equation}
$$



In [42]:
# prove that P is a symmetric matrix


Similarly, we say that a matrix $\textbf{A}$ is **skew-symmetric** if $\textbf{A}^T = -\textbf{A}$ (equivalently $a_{ij} = -a_{ji}$ for every entry $a_{ij}$ in $\textbf{A}$). The matrix $\textbf{Q}$ below is a skew-symmetric matrix.

$$
\begin{equation}
\textbf{Q} = \left[ \begin{array}{rrr} 0 & 1 & -4 \\ -1 & 0 & 5 \\ 4 & -5 & 0\end{array}\right] \hspace{1cm}
\end{equation}
$$


In [43]:
# prove that Q is a skew-symmetric matrix

## Identity matrices

An **identity matrix** is a square matrix that behaves similar to the number 1 with respect to ordinary multiplication.  Identity matrices, labeled with $\textbf{I}$, are made up of ones along the main diagonal, and zeros everywhere else.  Below is the $4 \times 4$ version of $\textbf{I}$.

$$
\begin{equation}
\textbf{I} = \left[ \begin{array}{ccc} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0\\ 0 & 0 & 0 & 1 \end{array}\right]
\end{equation}
$$

If $\textbf{A}$ is any other $4 \times 4$ matrix, multiplication with $\textbf{I}$ will produce $\textbf{A}$.  Furthermore it doesn't matter in this case which order the multiplication is carried out.

$$
\begin{equation}
\textbf{AI} = \textbf{IA} = \textbf{A}
\end{equation}
$$

The NumPy function $\texttt{eye}$ generates an identity matrix of the specified size.  Note we only need to provide $\texttt{eye}$ with one parameter since the identity matrix must be square.  We show here the product of $I$ with a random $5\times 5$ matrix.  

In [44]:
I_4 = np.eye(4)
I_4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
# prove the previous statements

## Matrix-vector multiplication

One special case of matrix multiplication deserves close attention, the case where one of the matrices is a vector.  This case is so important that it is commonly discussed separately and given a special name, **matrix-vector multiplication**.  Let's suppose that $\textbf{B}$ is our matrix and that its shape is $n \times m$, and $\textbf{y}$ is our vector which is $m \times 1$.  The product $\textbf{Py}$ then is a $n \times 1$ vector.  It is the relationship between this new vector and the columns of the matrix $\textbf{P}$ that makes this situation important.

Let's have a look with a specific example.

$$
\begin{equation}
\textbf{P}= \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]\hspace{1cm}
\textbf{y} = \left[ \begin{array}{r} 2 \\ -3 \\ 4 \end{array}\right]
\end{equation}
$$

In this case of matrix-vector multiplication, we can package the calculation a bit differently to better understand what is happening.

$$
\begin{equation}
\textbf{Py} = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]
\left[ \begin{array}{r} 2 \\ -3 \\ 4 \end{array}\right]=
2\left[ \begin{array}{r} 1 \\ 5 \\ 4 \\ 2 \end{array}\right] -
3\left[ \begin{array}{r} 3 \\ 2 \\ 2 \\ 2 \end{array}\right] +
4\left[ \begin{array}{r} -2 \\ 0 \\ -1 \\ 0 \end{array}\right] =
\left[ \begin{array}{r} -15\\ 4 \\ -2 \\ -2  \end{array}\right]
\end{equation}
$$

This is the same operation that we were doing before, but now we see that this product is a result of adding the columns of $\textbf{P}$ after first multiplying each by the corresponding entry in $\textbf{y}$.

## Test what you have learned

### Matrix algebra

Let A and B be two $4\times 4$ matrices respectively, such that:

$$
\mathbf{A}=\left[\begin{array}{cccc}
1 & 4 & 6 & 8 \\
2 & -5 & 3 & 7 \\
4 & 6 & 8 & 1 \\
7 & 3 & 5 & -2
\end{array}\right]
$$

$$
\mathbf{B}=\left[\begin{array}{cccc}
-1 & 1 & 2 & -2 \\
4 & 8 & -3 & 6 \\
2 & 5 & 1 & 3 \\
6 & 2 & 9 & 0
\end{array}\right]
$$

Calculate:

- $\mathbf{A}+\mathbf{B}$
- $\mathbf{A}^{\top}$
- $\mathbf{A B}$
- $\textbf{BA}$
- $3(\mathbf{A}+6 \mathbf{B})$
- $\operatorname{rank} \mathbf{A}$ y $\operatorname{rank}\textbf{B}$
- $\operatorname{det} \mathbf{A} y \operatorname{det} \mathbf{B}$
- $\mathbf{A}^{-1}$ y $\mathbf{B}^{-1}$

# Solving systems of linear equations using python -  a (very) quick introduction

## Application to linear systems

A very important example of matrix multiplication is that where a known matrix multiplies an *unknown* vector to produce a known vector.  If we let $\textbf{A}$ be the known matrix, $\textbf{b}$ be the known vector, and $\textbf{x}$ be the unknown vector, we can write the matrix equation $\textbf{Ax}=\textbf{b}$ to describe this scenario.  Let's write a specific example.

$$
\begin{equation}
\textbf{A}= \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right] \hspace{1cm}
\textbf{x}= \left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right] \hspace{1cm}
\textbf{b}= \left[ \begin{array}{r} 0 \\ 10 \\ 7 \\ 4  \end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
\textbf{Ax} = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]
\left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right]=
\left[ \begin{array}{r} 0\\ 10 \\ 7 \\ 4  \end{array}\right]= \textbf{b}
\end{equation}
$$

If we apply the definition of matrix multiplication we see that this single matrix equation $\textbf{Ax}=\textbf{b}$ in fact represents a system of linear equations.

$$
\begin{eqnarray*}
x_1 + 3x_2 - 2x_3 & = & 0\\
5x_1 + 2x_2 \quad\quad & = & 10 \\
4x_1 + 2x_2 - x_3 & = & 7 \\
2x_1 + 2x_2 \quad\quad & = & 4
\end{eqnarray*}
$$

In this context, the matrix $A$ is known as the **coefficient matrix**.

## General solver, <b>solve</b>:

<a> https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve </a>

In [46]:
from scipy.linalg import solve

### Options:

scipy.linalg.solve(a, b, sym_pos=False, lower=False, overwrite_a=False, overwrite_b=False, check_finite=True, assume_a='gen', transposed=False)

If we know the type of the coefficient matrix:

In [47]:
assume_a = 'gen'  # genéric (default)
assume_a = 'sym'  # symmetric matrix
assume_a = 'her'  # hermitian matrix
assume_a = 'pos'  # positive definite matrix

## Example

$$
\begin{array}{rr}
4 x_{1}+2 x_{2}+14 x_{3}= & 14 \\
2 x_{1}+17 x_{2}-5 x_{3}= & -101 \\
14 x_{1}-5 x_{2}+83 x_{3}= & 155
\end{array}
$$

In [48]:
import numpy as np

A = [[4,2,14],[2,17,-5],[14,-5,83]]
b = [14,-101,155]

x = solve(A,b)

In [49]:
A = np.array(A)
b = np.array(b)

solve(A,b)

array([ 3., -6.,  1.])

In [50]:
A = np.array(A)
b = np.array(b)

assume_a='pos'
solve(A,b,assume_a=assume_a)

array([ 3., -6.,  1.])

if we wrongly suggest the type of the coefficients matrix, we will obtain wrong results:

In [51]:
A = [[4,2,0],[2,17,-5],[14,-5,83]]
b = [14,-101,155]

A=np.array(A)
A  # Non symmetric

array([[ 4,  2,  0],
       [ 2, 17, -5],
       [14, -5, 83]])

In [52]:
A_c = solve(A,b) #correct solution
A_c

array([ 6.82570978, -6.65141956,  0.31545741])

In [53]:
A_sym = solve(A,b,assume_a='sym') # assuming symmetric
A_sym

array([ 6.64236378, -6.28472755,  1.48887183])

In [54]:
A_c - A_sym # != [0,0,0]

array([ 0.183346  , -0.36669201, -1.17341442])

In [55]:
A_c == A_sym

array([False, False, False])

### System of equations

Solve the following system of equations

$$\begin{aligned}
4 x_{1}+2 x_{2}+4 x_{3} &=20 \\
2 x_{1}+2 x_{2}+3 x_{3}+2 x_{4} &=36 \\
4 x_{1}+3 x_{2}+6 x_{3}+3 x_{4} &=60 \\
2 x_{2}+3 x_{3}+9 x_{4} &=122
\end{aligned}$$

Using

- PLU Decomposition (lu_solve)
- scipy's generic solver (solve)